### ISSUE TITLE
Unable to download Flickr8k dataset

### ISSUE THREAD

**Issue by PrinceOfDorne** [ayush2991/flickr8k#1]
I filled the required form on the standard site and they mailed me the link to the dataset. However, the links seem to broken as it raises an error "Site not found". Did you encounter the same error? How else can I download the dataset. In the worst case, can you share the dataset with me? It would be really helpful. Thanks in advance.

**Comment by ayush2991** [comment]
It looks like the dataset is not hosted on that server/path anymore as my links have stopped working as well. Unfortunately, redistributing the dataset is not allowed, so your best option might be to get in touch with the hosts and inform them of the problem. Maybe also try again in a couple of days/a week in case they've identified and fixed the issue by then. Closing this issue.

**Comment by PrinceOfDorne** [comment]
Okkk... Thanx

On 18-Feb-2019 1:14 AM, "Aayush Agarwal" <notifications@github.com> wrote:

It looks like the dataset is not hosted on that server/path anymore as my
links have stopped working as well. Unfortunately, redistributing the
dataset is not allowed, so your best option might be to get in touch with
the hosts and inform them of the problem. Maybe also try again in a couple
of days/a week in case they've identified and fixed the issue by then.
Closing this issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ayush2991/flickr8k/issues/1#issuecomment-464500007>,
or mute
the thread
